apiVersion: cache.cloud104.io/v1alpha1
kind: RedisCluster
metadata:
  name: cache-producao
  labels:
    app.kubernetes.io/name: rediscluster
    app.kubernetes.io/managed-by: redis-operator
spec:
  size: 3
  sentinelSize: 3
  redisImage: "redis:7.0-alpine"